
export const SET_COLLAPSE = 'SET_COLLAPSE'

export const SET_MENU_LIST= 'SET_MENU_LIST'

export const SET_SKIN = 'SET_SKIN'

export const SET_USER_INFO = 'SET_USER_INFO'

export const SET_PERMISSION_TREE_LIST = 'SET_PERMISSION_TREE_LIST'

export const SET_TOP_ACTIVE_INDEX = 'SET_TOP_ACTIVE_INDEX'

export const SET_LEFT_ACTIVE_INDEX = 'SET_LEFT_ACTIVE_INDEX'
