export const constTypeList = [
  {
    attribute_name: "单行文本", 
    front_type: 'singleRowText',
    attribute_code: "",
    max_value: 200, 
    min_value: 0, 
    min_length: 0, 
    value: "", 
    required: false, 
    precision: 1, 
    regexp: "",  
    max_length: 200, 
    unit: "",
    options: [{name: '', code: '', checked: false}],
    refCode: '',
    relationName: ''
  },
  {
    attribute_name: "多行文本", 
    front_type: 'multiRowText',
    attribute_code: "",
    max_value: 200, 
    min_value: 0, 
    min_length: 0, 
    value: "", 
    required: false, 
    precision: 1, 
    regexp: "",  
    max_length: 200, 
    unit: "",
    options: [{name: '', code: '', checked: false}],
    refCode: '',
    relationName: ''
  },
  {
    attribute_name: "整数", 
    front_type: 'int',
    attribute_code: "",
    max_value: 200, 
    min_value: 0, 
    min_length: 0, 
    value: "", 
    required: false, 
    precision: 1, 
    regexp: "",  
    max_length: 200, 
    unit: "",
    options: [{name: '', code: '', checked: false}],
    refCode: '',
    relationName: ''
  },
  {
    attribute_name: "小数", 
    front_type: 'float',
    attribute_code: "",
    max_value: 200, 
    min_value: 0, 
    min_length: 0, 
    value: "", 
    required: false, 
    precision: 1, 
    regexp: "",  
    max_length: 200, 
    unit: "",
    options: [{name: '', code: '', checked: false}],
    refCode: '',
    relationName: ''
  },
  {
    attribute_name: "日期", 
    front_type: 'dateTime',
    attribute_code: "",
    max_value: 200, 
    min_value: 0, 
    min_length: 0, 
    value: "", 
    required: false, 
    precision: 1, 
    regexp: "",  
    max_length: 200, 
    unit: "",
    options: [{name: '', code: '', checked: false}],
    refCode: '',
    relationName: ''
  },
  {
    attribute_name: "下拉菜单", 
    front_type: 'listSel',
    attribute_code: "",
    max_value: 200, 
    min_value: 0, 
    min_length: 0, 
    value: "", 
    required: false, 
    precision: 1, 
    regexp: "",  
    max_length: 200, 
    unit: "",
    options: [{name: '', code: '', checked: false}],
    refCode: '',
    relationName: ''
  },
  { 
    attribute_name: "单选",
    front_type: 'singleSel',
    attribute_code: "",
    max_value: 200, 
    min_value: 0, 
    min_length: 0, 
    value: "", 
    required: false, 
    precision: 1, 
    regexp: "",  
    max_length: 200, 
    unit: "",
    options: [{name: '', code: '', checked: false}],
    refCode: '',
    relationName: ''
  },
  {
    attribute_name: "多选",
    front_type: 'multiSel',
    attribute_code: "",
    max_value: 200, 
    min_value: 0, 
    min_length: 0, 
    value: "", 
    required: false, 
    precision: 1, 
    regexp: "",  
    max_length: 200, 
    unit: "",
    options: [{name: '', code: '', checked: false}],
    refCode: '',
    relationName: ''
  },
  {
    attribute_name: "从属关系",
    front_type: 'belongReference',
    attribute_code: "",
    max_value: 200, 
    min_value: 0, 
    min_length: 0, 
    value: "", 
    required: false, 
    precision: 1, 
    regexp: "",  
    max_length: 200, 
    unit: "",
    options: [{name: '', code: '', checked: false}],
    refCode: '',
    relationName: ''
  },
  {
    attribute_name: "连接关系",
    front_type: 'linkReference',
    attribute_code: "",
    max_value: 200, 
    min_value: 0, 
    min_length: 0, 
    value: "", 
    required: false, 
    precision: 1, 
    regexp: "",  
    max_length: 200, 
    unit: "",
    options: [{name: '', code: '', checked: false}],
    refCode: '',
    relationName: ''
  },
  {
    attribute_name: "属性分组",
    front_type: 'group',
    attribute_code: "",
    max_value: 200, 
    min_value: 0, 
    min_length: 0, 
    value: "", 
    required: false, 
    precision: 1, 
    regexp: "",  
    max_length: 200, 
    unit: "",
    options: [{name: '', code: '', checked: false}],
    refCode: '',
    relationName: ''
  }
]
